### ISSUE TITLE
If you read this

### ISSUE THREAD

**Issue by chengwei0427** [chengwei0427/LIO-Livox-modified#1]
If you are reading this, that means you are worried something 
![0207B41C](https://user-images.githubusercontent.com/20199999/163792950-efc3b20e-1b28-4ba3-9e58-c508396b9a2e.png). 

Let me know, and we could communicate here ![0207D42A](https://user-images.githubusercontent.com/20199999/163792969-81a4111f-14ad-4bb9-b8ef-00bb22a4af82.png).

**Comment by lhthq** [comment]
hi~great work！ will you  open  the  code  about  i-kdtree?  Thank you!

**Comment by chengwei0427** [comment]
> hi~great work！ will you open the code about i-kdtree? Thank you!

Thank you for your interest in this project.
I will upload this part of the code in May. And only the code for mode 0/1 will be upload.

**Comment by Thiszzz** [comment]
请问是把剔除动态点云那部分删除了吗

**Comment by chengwei0427** [comment]
> 请问是把剔除动态点云那部分删除了吗

是的。传统激光，用livox那种动态点剔除就不合适了。
