### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by LetusRoll** [chengwei0427/LIO-Livox-modified#10]
您好，我有个问题想请教一下，雷达线面残差那里，计算了个权重weight，weight计算公式中，分母用的是点在全局地图下的坐标：

T _weight = T(1) - T(0.9) * ceres::abs(ld2) / ceres::sqrt(ceres::sqrt(P_to_Map(0) * P_to_Map(0) + P_to_Map(1) * P_to_Map(1) + P_to_Map(2) * P_to_Map(2)));

请问这里是不是应该使用雷达坐标系下的坐标啊，如果使用全局地图的坐标，岂不是权重与行驶距离有关系了，感觉不太很合理。

**Comment by chengwei0427** [comment]
你好， @C-Xingyu 
Sorry for later reply.
你说的是正确的，可能是忘记改了。
