### ISSUE TITLE
关于适配livox avia雷达

### ISSUE THREAD

**Issue by Cxz-dev** [chengwei0427/LIO-Livox-modified#12]
您好！感谢您上传的代码工作
           我看了下代码并不支持avia雷达的接口，请问您打算添加这部分代码吗？如果没有，在lio-livox的基础上添加avia接口可以给我一些建议吗？我将在这issues下更新，期待您的回复谢谢！

**Comment by chengwei0427** [comment]
Hi, @Cxz-dev 

抱歉，才看到这个issue。

由于没有用过avia雷达，所以短期应该不会增加这个雷达的接口；

你可以参考前面特征提取部分的代码，添加一个即可；或者参考我开源的[Lidar_IMU_Localization](https://github.com/chengwei0427/Lidar_IMU_Localization)进行更改；
