### ISSUE TITLE
跑数据集时出错

### ISSUE THREAD

**Issue by pytorch1100** [chengwei0427/LIO-Livox-modified#4]
![image](https://user-images.githubusercontent.com/59380928/184463923-f755389a-16fd-4099-95c2-7afe73018ca5.png)
跑UrbanNav数据集（Velodyne）时出现上面的错误。

![image](https://user-images.githubusercontent.com/59380928/184463945-dd6611a3-ed2c-40d5-bc96-83e0fce5e532.png)
跑UrbanLoco数据集（robosense）时出现上面的错误。希望大佬解答一下。

**Comment by chengwei0427** [comment]
你好，感谢关注；
从上面来看，是解析数据格式时，有些数据格式没有找到，可能是配置有问题，你可以检查一下你的激光类型配置；

**Comment by pytorch1100** [comment]
好的，我再去看看。
