### ISSUE TITLE
适配源码

### ISSUE THREAD

**Issue by wodlige** [chengwei0427/LIO-Livox-modified#6]
应该怎么适配呢，我把您的功能包直接和lio-livox功能包覆盖在一起后好像编译不了，我怀疑是cmakelist.txt文件还有package.xml文件有问题但是不知道怎么改，还是说我适配的有问题？

**Comment by chengwei0427** [comment]
你可以单独下载这个包去编译使用；

**Comment by wodlige** [comment]
我试了编译不成功，我怀疑是cmakelist.txt文件还有package.xml文件配置有问题

**Comment by chengwei0427** [comment]
cmakelists文件需要自己去修改一下的。
最简单的操作，就是把特征提取部分，放到LIO-Livox代码里，然后在LIO-Livox的cmakelists文件中增加一下特征提取部分，替换原来的特征提取，就可以使用了。

**Comment by chengwei0427** [comment]
把featureExtract.cpp及相关的头文件，放到LIO-Livox里，cmakelists里增加一下对应的编译语句；

**Comment by wodlige** [comment]
您好，可以发一份完整的源码吗，我修改了好久但还是编译不通过，麻烦您了。
