### ISSUE TITLE
Fatal Error: can't find "cloud_info.h"

### ISSUE THREAD

**Issue by 777learn** [chengwei0427/LIO-Livox-modified#7]
I am unable to run catkin_make because and getting Invoking "make -j8 -l8" failed
. I think this is due to -> 

featureExtract.cpp:28:10: fatal error: cloud_info.h: No such file or directory
   28 | #include "cloud_info.h"
   
 How to resolve this ? I couldn't find the file anywhere else in the repo.
![Screenshot from 2022-09-06 14-13-39](https://user-images.githubusercontent.com/112937120/188593030-6e3a05e3-10b2-4ad6-8986-8287f3153e1f.png)
![Screenshot from 2022-09-06 14-13-44](https://user-images.githubusercontent.com/112937120/188593055-5596565e-e385-4af5-8fb8-a7431c0f213a.png)

Kindly help.

**Comment by chengwei0427** [comment]
Try to execute multiple times `catkin_make`
https://github.com/chengwei0427/LIO-Livox-modified/blob/84133d5893ef03daec8bbe57f12e6eedab028093/CMakeLists.txt#L47

**Comment by chengwei0427** [comment]
Upload the `cloud_info.h`, and you can update the code.

https://github.com/chengwei0427/LIO-Livox-modified/blob/e0d882eb6798a0aea0d6d343dee58f3c4f7ee3ff/include/cloud_info.h

**Comment by 777learn** [comment]
Hi, thanks it worked, had to comment the Robosense part later, as it was also throwing an error. I am facing another issue, which i am raising separately.
