### ISSUE TITLE
dataset needed, unable to run with livox-horizon

### ISSUE THREAD

**Issue by 777learn** [chengwei0427/LIO-Livox-modified#8]
Hi i tried horizon.launch but it doesn't run obviously due to the lack of scanregistration.cpp.

I tried running run.launch with livox-horizon data available here - 
https://github.com/Livox-SDK/livox_horizon_loam and it doesn't work

Will the current run.launch support livox-horizon or livox (fov 38 degrees) or any other solid state/directional lidar with smaller FoVs?

Which Lidars would be supported and can you point me/provide me some dataset which is compatible with your code.

Help would be really grateful.

Thanks.

**Comment by chengwei0427** [comment]
`Will the current run.launch support livox-horizon or livox (fov 38 degrees) or any other solid state/directional lidar with smaller FoVs?`
Sorry, current code maynot support horizon lidar.

`Which Lidars would be supported and can you point me/provide me some dataset which is compatible with your code.`
You could test the code with the dataset such as lio-sam, fast_lio ,urbanNavDataset, NCLT etc.
You can also  test with the `ESKF_lio` in my github .

**Comment by 777learn** [comment]
`Sorry, current code maynot support horizon lidar.`
>  No issues, is livox mid-40, and not horizon supported ?

`You could test the code with the dataset such as lio-sam, fast_lio ,urbanNavDataset, NCLT etc. You can also test with the `ESKF_lio` in my github .`
>Thanks i will try on these

**Comment by chengwei0427** [comment]
Sorry, I donnot have a horizon livox lidar or any dataset, Maybe you can write a featextract yourself.



---Original---
From: ***@***.***&gt;
Date: Tue, Sep 6, 2022 18:08 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chengwei0427/LIO-Livox-modified] dataset needed, unable to run with livox-horizon (Issue #8)




 
Sorry, current code maynot support horizon lidar.
  
No issues, is livox (the normal one, and not horizon supported ?)
  
You could test the code with the dataset such as lio-sam, fast_lio ,urbanNavDataset, NCLT etc. You can also test with the ESKF_lio in my github .
  
Thanks i will try on these
