### ISSUE TITLE
关于里程计没有position值

### ISSUE THREAD

**Issue by cyhasuka** [chengwei0427/LIO-Livox-modified#9]
您好，首先谢谢您分享您的工作。我在运行代码时发现/odometry_mapped这一topic输出的里程计只有orientation，position的值均为0.请问是由于PoseEstimation未做更改导致的吗，您后期有没有将其提交到仓库的打算？谢谢您并期待您的回复！

**Comment by chengwei0427** [comment]
@cyhasuka  你好，感谢关注，最新的代码放在了这个仓库[Lidar_IMU_Localization](https://github.com/chengwei0427/Lidar_IMU_Localization)，你可以再看下哈！
